service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

custom:
  webpackIncludeModules: true
  serverless-offline:
    port: 3001

functions:
  postSignup:
    handler: functions/users/signup.postSignup
    environment:
      PGUSER: ${file(./serverless.env.yml):POSTGRES.PGUSER}
      PGHOST: ${file(./serverless.env.yml):POSTGRES.PGHOST}
      PGPASSWORD: ${file(./serverless.env.yml):POSTGRES.PGPASSWORD}
      PGDATABASE: ${file(./serverless.env.yml):POSTGRES.PGDATABASE}
      PGPORT: ${file(./serverless.env.yml):POSTGRES.PGPORT}
      DB_CONNECT: ${file(./serverless.env.yml):dev.DB_CONNECT}
      SECRET: ${file(./serverless.env.yml):dev.SECRET}
    events:
      - http:
          method: post
          path: api/user/signup
          cors: true
          integration: lambda
          
  postLogin:
    handler: functions/users/login.postLogin
    environment:
      DB_CONNECT: ${file(./serverless.env.yml):dev.DB_CONNECT}
      SECRET: ${file(./serverless.env.yml):dev.SECRET}
    events:
      - http:
          method: post
          path: api/user/login
          cors: true
          integration: lambda
